### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'dist'`

### ISSUE THREAD

**Issue by salimep** [Juniper/contrail-webui-third-party#14]
Getting below exception  while fetching the package for contrail build

`root@salim:~/salim# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"`

` python3 third_party/fetch_packages.py
third_party/fetch_packages.py:139: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if ret is not 0:
Traceback (most recent call last):
  File "third_party/fetch_packages.py", line 307, in <module>
    main()
  File "third_party/fetch_packages.py", line 280, in main
    ProcessPackage(object)
  File "third_party/fetch_packages.py", line 182, in ProcessPackage
    if not PlatformRequires(pkg):
  File "third_party/fetch_packages.py", line 170, in PlatformRequires
    info = PlatformInfo()
  File "third_party/fetch_packages.py", line 143, in PlatformInfo
    (distname, version, _) = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'`

**Comment by salimep** [comment]
issue resolved
by modifying  existing codes as shown in below

'
def PlatformInfo():
    (distname, version, _) = platform.mac_ver()
    return (distname.lower(), version)

'
